const USERNAME_RE = /^[a-zA-Z0-9._-]{3,50}$/;

function buildSnapcodeUrl(username) {
  return `https://app.snapchat.com/web/deeplink/snapcode?username=${username}&type=SVG&bitmoji=enable`;
}

async function checkSnapchatExistence(username) {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 8000);
    const res = await fetch(`https://www.snapchat.com/add/${username}`, {
      headers: { 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1' },
      signal: controller.signal,
    });
    clearTimeout(timer);
    return res.ok;
  } catch { return false; }
}

async function scrapeProfileData(username) {
  const urls = [`https://www.snapchat.com/@${username}`, `https://www.snapchat.com/add/${username}`];
  for (const url of urls) {
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 10000);
      const res = await fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
          'Accept-Language': 'ar,en;q=0.9',
        },
        signal: controller.signal,
      });
      clearTimeout(timer);
      if (!res.ok) continue;
      const html = await res.text();

      const metaMatch = (patterns) => {
        for (const p of patterns) { const m = html.match(p); if (m && m[1]) return m[1]; }
        return undefined;
      };

      let displayName = metaMatch([
        /property="og:title"s+content="([^"]+)"/i,
        /content="([^"]+)"s+property="og:title"/i,
        /"displayName"s*:s*"((?:[^"\]|\\.)*)"/,
      ]);
      if (displayName) {
        displayName = displayName
          .replace(/s*[|·-–]s*snapchat.*$/i, '')
          .replace(/s*(@[^)]+).*$/, '')
          .replace(/^snapchats+S+s+/i, '')
          .trim();
        if (!displayName || displayName.toLowerCase() === 'snapchat') displayName = undefined;
      }

      const rawBio = metaMatch([
        /name="description"s+content="([^"]+)"/i,
        /content="([^"]+)"s+name="description"/i,
      ]);
      let lastActive = null;
      if (rawBio) {
        const dateMatch = rawBio.match(/(d{2})/(d{2})/(d{4})/);
        if (dateMatch) lastActive = `${dateMatch[2]}/${dateMatch[1]}/${dateMatch[3]}`;
      }
      const isAutoGenerated = rawBio && (
        rawBio.includes(`(@${username}`) || rawBio.includes('(@') ||
        /d{2}/d{2}/d{4}/.test(rawBio) || /snapchat/i.test(rawBio)
      );
      const jsonBioMatch = html.match(/"bio"s*:s*"((?:[^"\]|\\.)*)"/);
      const jsonBio = jsonBioMatch && jsonBioMatch[1] ? jsonBioMatch[1].replace(/\n/g, '
').replace(/\"/g, '"').trim() : undefined;
      let bio;
      if (jsonBio && jsonBio.length > 0 && jsonBio.length < 500) bio = jsonBio;
      else if (rawBio && !isAutoGenerated && rawBio.length < 300) bio = rawBio;

      const avatarUrl = metaMatch([
        /property="og:image"s+content="([^"]+)"/i,
        /content="([^"]+)"s+property="og:image"/i,
      ]);

      const sm = html.match(/"subscriberCount"s*:s*(d+)/);
      const subscriberCount = sm ? parseInt(sm[1], 10) : null;

      return { displayName, bio, avatarUrl, bgUrl: undefined, subscriberCount, lastActive, stories: [], spotlights: [], highlights: [] };
    } catch (_) { /* try next url */ }
  }
  return {};
}

async function getSnapProfile(username) {
  const lc = username.toLowerCase();
  const base = {
    exists: true, username: lc, displayName: lc, bio: '',
    avatarUrl: '', bgUrl: '', snapcodeUrl: buildSnapcodeUrl(lc),
    subscriberCount: null, snapScore: null, lastActive: null,
    stories: [], spotlights: [], highlights: [], lenses: [],
    profileUrl: `https://www.snapchat.com/@${lc}`,
  };
  const [exists, profileData] = await Promise.all([checkSnapchatExistence(lc), scrapeProfileData(lc)]);
  return {
    ...base, exists,
    displayName: profileData.displayName || lc,
    bio: profileData.bio || '',
    avatarUrl: profileData.avatarUrl || '',
    bgUrl: profileData.bgUrl || '',
    subscriberCount: profileData.subscriberCount !== undefined ? profileData.subscriberCount : null,
    lastActive: profileData.lastActive || null,
    stories: profileData.stories || [],
    spotlights: profileData.spotlights || [],
    highlights: profileData.highlights || [],
  };
}

const HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type',
};

export const handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: HEADERS, body: '' };
  }

  const username = (event.queryStringParameters && event.queryStringParameters.username) ||
                   decodeURIComponent(event.path.split('/').filter(Boolean).pop() || '');

  if (!username || !USERNAME_RE.test(username)) {
    return {
      statusCode: 200,
      headers: HEADERS,
      body: JSON.stringify({
        exists: false, username: username || '', displayName: '', bio: '',
        avatarUrl: '', bgUrl: '', snapcodeUrl: '', subscriberCount: null,
        snapScore: null, lastActive: null, stories: [], spotlights: [],
        highlights: [], lenses: [], profileUrl: '',
        error: 'المعرف غير صالح — يجب أن يتكون من 3 أحرف على الأقل',
      }),
    };
  }

  try {
    const profile = await getSnapProfile(username);
    if (!profile.exists) {
      return {
        statusCode: 200,
        headers: HEADERS,
        body: JSON.stringify({
          ...profile,
          exists: false,
          error: 'هذا الحساب غير موجود على سناب شات',
        }),
      };
    }
    return { statusCode: 200, headers: HEADERS, body: JSON.stringify(profile) };
  } catch (_) {
    return {
      statusCode: 200,
      headers: HEADERS,
      body: JSON.stringify({
        exists: false, username, displayName: username, bio: '',
        avatarUrl: '', bgUrl: '', snapcodeUrl: buildSnapcodeUrl(username),
        subscriberCount: null, snapScore: null, lastActive: null,
        stories: [], spotlights: [], highlights: [], lenses: [],
        profileUrl: `https://www.snapchat.com/@${username}`,
        error: 'تعذّر الاتصال بسناب شات. يرجى المحاولة لاحقاً',
      }),
    };
  }
};
